manifest:
  defaults:
    remote: zephyrproject

  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: zenoh-pico
      url-base: https://github.com/eclipse-zenoh

  projects:
    - name: zephyr
      remote: zephyrproject
      repo-path: zephyr
      revision: v4.1.0
      path: zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_espressif
          - mbedtls
          - picolibc
    
    - name: zenoh-pico
      remote: zenoh-pico
      repo-path: zenoh-pico
      revision: 1.4.0
      path: modules/lib/zenoh-pico

  self:
    path: .
